gerenciador_tarefa/urls.py
from django.urls import path
from .views import tarefa_views
from .views import usuario_views

urlpatterns = [
    path('', tarefa_views.listar_tarefas, name='listar_tarefas'),
    path('cadastrar/', tarefa_views.cadastrar_tarefa, name='cadastrar_tarefas'),
    path('editar/<int:id>', tarefa_views.editar_tarefa, name='editar_tarefa'),
    path('remover/<int:id>', tarefa_views.remover_tarefa, name='remover_tarefa'),
    path('cadastrar_usuario/', usuario_views.cadastrar_usuario, name='cadastrar_usuario'),
    path('login/', usuario_views.logar_usuario, name='logar_usuario'),
    path('deslogar_usario', usuario_views.deslogar_usuario, name='deslogar_usuario'),
]

semanadjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gerenciador_tarefa.urls'))
]

gerenciador_tarefa/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Tarefa(models.Model):
    PRIORIDADE_OPCOES = [
        ('N', 'Normal'),
        ('A', 'Alta'),
        ('B', 'Baixa')
    ]
    titulo = models.CharField(max_length=30, null=False, blank=False, verbose_name='Título')
    descricao = models.CharField(max_length=100, null=False, blank=False, verbose_name='Descrição')
    data_expiracao = models.DateField(null=False, blank=False, verbose_name='Data de Expiração')
    prioridade = models.CharField(max_length=1, choices=PRIORIDADE_OPCOES, null=False, blank=False, verbose_name='Prioridade')
    usuario = models.ForeignKey(User, verbose_name='Usuário', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Tarefas'

    def __str__(self):
        return self.titulo

gerenciador_tarefa/forms.py
from django import forms
from .models import Tarefa

class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        exclude = ('usuario', )
        fields = '__all__'

gerenciador_tarefa/views/tarefa_views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from gerenciador_tarefa.forms import TarefaForm
from gerenciador_tarefa.entidades import tarefa
from gerenciador_tarefa.services import tarefa_services
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def listar_tarefas(request):
    tarefas = tarefa_services.listar_tarefas(request.user)
    return render(request, 'tarefas/listar_tarefas.html', {'tarefas': tarefas, 'listagem_page': 'active'})

@login_required
def cadastrar_tarefa(request):
    if request.method == 'POST':
        form_tarefa = TarefaForm(request.POST)
        if form_tarefa.is_valid():
            titulo = form_tarefa.cleaned_data['titulo']
            descricao = form_tarefa.cleaned_data['descricao']
            data_expiracao = form_tarefa.cleaned_data['data_expiracao']
            prioridade = form_tarefa.cleaned_data['prioridade']
            nova_tarefa = tarefa.Tarefa(titulo=titulo,
                                        descricao=descricao,
                                        data_expiracao=data_expiracao,
                                        prioridade=prioridade,
                                        usuario=request.user)

            tarefa_services.cadastrar_tarefa(nova_tarefa)
            return redirect('listar_tarefas')
    else:
        form_tarefa = TarefaForm()
    return render(request, 'tarefas/form_tarefa.html', {'form_tarefa': form_tarefa, 'cadastro_page': 'active'})

@login_required
def editar_tarefa(request, id):
    tarefa_bd = tarefa_services.listar_tarefa_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse('Não permitido')
    form_tarefa = TarefaForm(request.POST or None, instance=tarefa_bd)
    if form_tarefa.is_valid():
        titulo = form_tarefa.cleaned_data['titulo']
        descricao = form_tarefa.cleaned_data['descricao']
        data_expiracao = form_tarefa.cleaned_data['data_expiracao']
        prioridade = form_tarefa.cleaned_data['prioridade']
        nova_tarefa = tarefa.Tarefa(titulo=titulo,
                                    descricao=descricao,
                                    data_expiracao=data_expiracao,
                                    prioridade=prioridade,
                                    usuario=request.user)

        tarefa_services.editar_tarefa(tarefa_bd, nova_tarefa)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/form_tarefa.html', {'form_tarefa': form_tarefa})

@login_required
def remover_tarefa(request, id):
    tarefa_bd = tarefa_services.listar_tarefa_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse('Não permitido')
    if request.method == 'POST':
        tarefa_services.remover_tarefa(tarefa_bd)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/confirma_exclusao.html', {'tarefa': tarefa_bd})

gerenciador_tarefa/views/usuario_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

def cadastrar_usuario(request):
    if request.method == 'POST':
        form_usuario = UserCreationForm(request.POST)
        if form_usuario.is_valid():
            form_usuario.save()
            return redirect('listar_tarefas')
    else:
        form_usuario = UserCreationForm()
    return render(request, 'usuarios/form_usuario.html', {'form_usuario': form_usuario, 'cadastro_user_page':'active'})

def logar_usuario(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        usuario = authenticate(request, username=username, password=password)
        if usuario is not None:
            login(request, usuario)
            return redirect('listar_tarefas')
        else:
            messages.error(request, 'As credenciais do usuário estão incorretas')
            return redirect('logar_usuario')
    else:
        form_login = AuthenticationForm()
    return render(request, 'usuarios/login.html', {'form_login': form_login, 'login_page': 'active'})


def deslogar_usuario(request):
    logout(request)
    return redirect('logar_usuario')

gerenciador_tarefa/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Gerenciador de Tarefa - {% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'gerenciador_tarefa/css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Gerenciador de Tarefas</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item {{ listagem_page }}">
        <a class="nav-link" href="{% url 'listar_tarefas' %}">Listar Tarefas</a>
      </li>
      <li class="nav-item {{ cadastro_page }}">
        <a class="nav-link" href="{% url 'cadastrar_tarefas' %}">Cadastrar Tarefas</a>
      </li>
        <li class="nav-item {{ cadastro_user_page }}">
        <a class="nav-link" href="{% url 'cadastrar_usuario' %}">Cadastrar Usuário</a>
      </li>
        <li class="nav-item {{ login_page }}">
        <a class="nav-link" href="{% url 'logar_usuario' %}">Entrar</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'deslogar_usuario' %}">Sair</a>
      </li>

    </ul>
  </div>
</nav>
    <main class="container">
        <div class="card">
            <div class="card-header text-center">
                <h1>{% block cardtitle %} {% endblock cardtitle %}</h1>
            </div>
            <div class="card-body">
                {% block card_body %}

                {% endblock card_body %}
            </div>
            <div class="card-footer">
                {% block card_footer %}

                {% endblock card_footer %}
            </div>
        </div>
        {% block content %}


        {% endblock content %}
    </main>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

gerenciador_tarefa/templates/tarefas/confirma_exclusao.html
{% extends 'base.html' %}
{% load meus_filtros %}
{% block title %}
Remover Tarefa
{% endblock title %}

{% block cardtitle %}
Confirma a exclusão da Tarefa?
{% endblock cardtitle %}
{% block card_body %}
<div class="card mb-12">
    <div class="card-header">
        {{ tarefa.get_prioridade_display }}
    </div>
    <div class="card-body">
        <h5 class="card-title">
            {{ tarefa.titulo }}
        </h5>
        <p class="card-text">
            {{ tarefa.descricao }}
        </p>
        <p class="card-text">
            Data Limite: {{ tarefa.data_expiracao }}
        </p>
    </div>
    <div class="card-footer">
        <form method="POST">
        {% csrf_token %}
            <button class="btn btn-danger" type="submit">Remover</button>
        </form>
    </div>
{% endblock card_body %}

gerenciador_tarefa/templates/tarefas/form_tarefa.html
{% extends 'base.html' %}
{% load meus_filtros %}
{% block title %}
Cadastrar Tarefa
{% endblock title %}

{% block cardtitle %}
Cadastro de Tarefas
{% endblock cardtitle %}


    {% block card_body %}
    <form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="titulo">Título: </label>
        {{ form_tarefa.titulo | addclass:'form-control' }}
        {{ form_tarefa.titulo.errors }}
    </div>
        <div class="form-group">
        <label for="descricao">Descrição: </label>
        {{ form_tarefa.descricao | addclass:'form-control' }}
            {{ form_tarefa.descricao.errors }}
    </div>
        <div class="form-group">
        <label for="data_expiracao">Data de Expiração: </label>
        {{ form_tarefa.data_expiracao | addclass:'form-control' }}
            {{ form_tarefa.data_expiracao.errors }}
    </div>
        <div class="form-group">
        <label for="prioridade">Prioridade: </label>
        {{ form_tarefa.prioridade | addclass:'form-control' }}
            {{ form_tarefa.prioridade.errors }}
        </div>

    {% endblock card_body %}
    {% block card_footer %}
<div class="form-group">
                <input type="submit" class="btn btn-primary" value="Salvar"></input>
        </div>
    {% endblock card_footer %}
</form>

gerenciador_tarefa/templates/tarefas/listar_tarefas.html
{% extends 'base.html' %}
{% block title %}
Listagem de tarefa
{% endblock title %}
{% block cardtitle %}
Listagem de Tarefas
{% endblock cardtitle %}
{% block card_body %}
{% for tarefa in tarefas %}
<div class="card mb-3">
    <div class="card-header">
        {{ tarefa.get_prioridade_display }}
    </div>
    <div class="card-body">
        <h5 class="card-title">
            {{ tarefa.titulo }}
        </h5>
        <p class="card-text">
            {{ tarefa.descricao }}
        </p>
        <p class="card-text">
            Data Limite: {{ tarefa.data_expiracao }}
        </p>
    </div>
    <div class="card-footer">
        <a class="btn btn-secondary" href="{% url 'editar_tarefa' tarefa.id %}">Editar</a>
        <a class="btn btn-danger" href="{% url 'remover_tarefa' tarefa.id %}">Remover</a>
    </div>
</div>
{% endfor %}
{% endblock card_body %}
{% block card_footer %}
    <a href="{% url 'cadastrar_tarefas' %}" class="btn btn-primary float-right">Nova Tarefa</a>
{% endblock card_footer %}

gerenciador_tarefa/templates/usuarios/form_usuario.html
{% extends 'base.html' %}
{% load meus_filtros %}
{% block title %}
Cadastrar Usuário
{% endblock title %}

{% block cardtitle %}
Cadastro de Usuário
{% endblock cardtitle %}

{% block card_body %}
<form method="POST">
{% csrf_token %}
    <div class="form-group">
        <label for="username">Nome de Usuário: </label>
        {{ form_usuario.username | addclass:'form-control'}}
        {{ form_usuario.username.errors }}
    </div>
    <div class="form-group">
        <label for="password">Senha: </label>
        {{ form_usuario.password1 | addclass:'form-control'}}
        {{ form_usuario.password1.errors }}
    </div>
    <div class="form-group">
        <label for="pass_confirm">Confirmação de Senha: </label>
        {{ form_usuario.password2 | addclass:'form-control' }}
        {{ form_usuario.password2.errors }}
    </div>
    <div class="form-group">
        <input type="submit" value="Cadastrar" class="btn btn-primary">
    </div>

</form>


{% endblock card_body %}

gerenciador_tarefa/templates/usuarios/login.html
{% extends 'base.html' %}
{% load meus_filtros %}
{% block title %}
Login de Usuário
{% endblock title %}

{% block cardtitle %}
Login de Usuário
{% endblock cardtitle %}
{% block card_body %}
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="username">Nome de Usuário</label>
        {{ form_login.username |addclass:'form-control'}}
    </div>
    <div class="form-group">
        <label for="password">Senha: </label>
        {{ form_login.password |addclass:'form-control'}}
    </div>
    <div class="form-group">
        <input type="submit" value="Entrar" class="btn btn-primary">
    </div>
</form>
{% endblock card_body %}
{% block card_footer %}
{% for message in messages %}
    <div class="alert-danger">
        {{ message }}
    </div>
    {% endfor %}
{% endblock card_footer %}